rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.2
  - ruby-head
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  exclude:
    - rvm: 2.1.5
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
